Fix the file descriptors leak
GolangLessons/url-shortener pull request #5
Opened 2023-07-06 00:50 UTC by ypaxu

Fix #4

2023-07-07 11:28 UTC, JustSkiv requested changes
Фикс хороший, но к тесту есть вопросы

2023-07-07 11:28 UTC, JustSkiv commented on internal/lib/api/api_test.go
> +	_, _ = api.GetRedirect(url)
Тут неплохо бы проверить наличие ошибки

2023-07-07 11:28 UTC, JustSkiv commented on internal/lib/api/api_test.go
> +	_, _ = api.GetRedirect(url)
И тут тоже надо проверить ошибку. Иначе может возникнуть ситуация, когда функция не работает, а тест успешно проходит.

2023-07-07 11:28 UTC, JustSkiv commented on internal/lib/api/api_test.go
> +	beforeCall := countOpenFileDescriptors(t)
Имеет смысл вызвать функцию `countOpenFileDescriptors` до первого вызова `GetRedirect`, чтобы проверить, что значение вообще меняется

2023-07-07 11:28 UTC, JustSkiv commented on internal/lib/api/api_test.go
> +	if err != nil {
можно проще: require.NoError(err)

2023-07-07 11:28 UTC, JustSkiv commented on internal/lib/api/api_test.go
> +	command := fmt.Sprintf("lsof -p %v", os.Getpid())
Во вспомогательных функциях нужно в начале вызывать t.Helper()

2023-07-07 11:28 UTC, JustSkiv commented on internal/lib/api/api_test.go
> +	if err != nil {
У функции смешанная ответственность. С одной стороны, она просто возвращает значение, с другой - фэйлит тест. Лучше чтобы она здесь возвращала ошибку, а проверять мы её будем выше.

2023-07-07 11:28 UTC, JustSkiv commented on internal/lib/api/api_test.go
> +package api_test
Тест специфичен, он запустится только на linux / mac. Поэтому нужно добавить ограничение сборки:

//go:build darwin || linux

2023-07-07 11:28 UTC, JustSkiv commented on internal/lib/api/api_test.go
> +	return len(lines) - 1
Мелкое замечание: перед return обычно ставят пустую строку (я позже прикручу линтер на такие вещи)

2023-07-08 15:11 UTC, ypaxu commented
Тест - это скорее PoC на тему "а как это проверить" и его конечно можно улучшить. Для меня тут главный вопрос в том, что нужен ли такой тест который полагается на внешние факторы (наличие соединиения с example.com и то что этот сайт вообще работает).
PS: вообще-то, `api_test.go` попал в PR по моему не знанию того, что новые коммиты в бранч автоматически добавляются в PR :)

2023-07-08 18:18 UTC, JustSkiv approved these changes

2023-07-08 18:19 UTC, JustSkiv commented
Ну, тест был хорошей идеей, зря ты его убрал. Надо было только чуток причесать. Но без него тоже норм

2023-07-08 18:20 UTC, merged